print("请输入第一个数字")
input1 = input()
print("请输入第二个数字")
input2 = input()
num1 = int(input1)
num2 = int(input2)
print("两个数的和是",num1+num2)
print("两个数的差是",num1-num2)
print("两个数的积是",num1*num2)
print("两个数的商是",num1/num2)
